baseURL = 'https://nebula0.github.io/'
languageCode = 'en-us'
title = 'Explosion Group Paper collection'
theme = "mainroad"
[Author] # Used in authorbox
  name = "README"
  bio = "OuO"


[Params]
  description = "arXiv paper collection for rescarch" # Site description. Used in meta description
  copyright = "nebula0" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["new_article", "article"] # Specify section pages to show on home page and the "Recent articles" widget # folder name under content directory ex: ["posts", "article"]
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = false # Enable MathJax
  mathjaxPath = "https://static.arxiv.org/MathJax-2.7.3/MathJax.js" #"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX" #"TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

  # DEPRECATED PARAMS
  subtitle = "What I can't create, I do not understand" # Deprecated in favor of .Site.Params.logo.subtitle
  highlightColor = "f99b03" # Deprecated in favor of .Site.Params.style.vars.highlightColor

[Params.style.vars]
  highlightColor = "#f99b03" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "img/cat.jpg" # Logo image. Path relative to "static"
  title = "Explosion Group" # Logo title, otherwise will use site title
  subtitle = "research field related paper collection" # Logo subtitle

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["categories", "taglist", "recent", "social", "languages", "search"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.search]
  url = "https://google.com/search"
  input.name = "sitesearch"
  input.pre = ""
